server:
  port: 80

spring:
  datasource:
    url: jdbc:oracle:thin:@49.***.***.***:1521/XEPDB1
    username: share_project
    password: happy
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true